trigger:
- azure-pipelines

pool:
  name: ubuntu-agent

steps:
- task: AzureKeyVault@2
  displayName: Azure Key Vault
  inputs:
    azureSubscription: 'webapp-ser_conn'
    #'mid-service_connection-webapp
    KeyVaultName: webapp-kv001
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  displayName: Create secret files
  inputs:
    script: | 
     echo $(MUSTAFASAYED) > secret1.txt
     echo $(DBSECRET001)  > secret2.txt

- task: CopyFiles@2
  displayName: Copy secret files
  inputs:
    Contents: |
      secret1.txt
      secret2.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SecretsArtifactStorage'
    artifact: secrets
    publishLocation: 'Container'
