trigger:
- main

pool:
 name: ubuntu-agent



steps:
- script: echo "start running steps ..."

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    cd ~
    npm install
    npm run build

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    cd ~
    pip install -r requirements.txt

- script: |
    echo "finished. the job ran successfully..."
    echo "Have a good day"